#### 8.别让异常逃离析构函数



考虑这样一种情况

```
class Widget{
public:
	~Widget(){}
};
void doSomething(){
	std::vector<Widget>v;
}
当vector v被销毁，会销毁其内含所有的Widgets。假如里面含有是个Widgets，而在析构第一个元素期间，有个异常被跑出。其他九个还是应该被销毁（否则他们保存的任何资源都会发生泄漏），因此v应该调用他们个个析构函数。但是假如接下来析构函数又抛出异常。有两个同时作用的异常，会导致不明确行为或者结束执行。

举个例子
class DBConnection{
public:
	static DBConnection create();
	void close();//关闭联机，失败会抛出异常。
}
为了确保客户不会忘记在DBConnection对象身上调用close(),创建一个用来管理DBConnection资源的class，并在其析构函数中调用close。

class DBConn{
public:
	~DBConn(){
		db.close();
	}
private:
	DBConnection db;
};

只要能调用close成功就还好，但如果该调用导致异常，DBConn析构函数就会传波异常，就是允许它离开这个析构函数。那会造成问题。会造成并没有关闭资源

```

两个办法解决这个问题：

* 如果close抛出异常就结束程序。通常通过调用abort完成

  ```
  DBConn::~DBConn(){
  	try{db.close();}
  	catch(){
  		std::abort();
  	}
  }
  ```

* 吞下因调用close而发生的异常：

  ```
  DBConn::~DBConn(){
  	try{db.close();}
  	catch(){
  		这里记录一下close调用失败；
  	}
  }
  但是吞下异常不太好，但是吞下异常相比于异常逃离析构函数会好很多。
  
  ```

一个较佳的策略是设计DBConn接口，使其客户有机会对可能出现的问题作出反应。例如DBConn自己可以提供一个close函数，因为赋予客户一个机会得以处理异常。，追踪close函数是否被调用，如果没有被调用则强制结束程序或吐下异常

```
class DBConn{
public:
	void close(){
		db.close();
		closed= true;
	}
	~DBConn(){
		if(!closed){
			try{
				db.close();
			}
			catch(){
				这里结束程序或者吞下异常。
				}
		}
	}
private:
	DBConnection db;
	bool closed;
}
```

把调用close的责任从DBConn析构函数手上移到DBConn客户手上（双保险）。

如果用户不自己调用则会依赖DBConn析构函数去调用close。



总结：

* 析构函数绝对不要吐出异常。如果一个被析构函数调用的函数可能抛出异常，析构函数应该捕捉任何异常。
* 如果客户需要对某个操作函数运行期间抛出的异常作出反应，那么class应该提供一个普通函数执行该操作。